
- name: Create db container and connect to network
  docker_container:
    name: database
    image: valkyriehd/database:latest
    volumes:
      - /data/:/var/lib/postgresql/data
    env:
      POSTGRES_PASSWORD: pwd
    networks:
      - name: app-network
